### ISSUE TITLE
Is it possible to track GVL hold time as well?

### ISSUE THREAD

**Issue by gstark** [Shopify/gvltools#2]
Thanks for sharing this gem. I'm interested in gathering GVL data and tracking this for web/sidekiq transactions.

In addition to tracking the amount of time threads wait for the GVL, is it possible to track how long they were holding the GVL? I attempted this in [a fork](https://github.com/gstark/gvltools/commit/20370e10552c9bac96db87ae5a1839fd48267e66), and while I can get the `GlobalTimer` to count GVL hold time, the `LocalTimer` is always `0`. I suspect this is due to a difference in which thread is active when the callback is fired for `RUBY_INTERNAL_THREAD_EVENT_SUSPENDED` but I am not 100% sure.

**Comment by casperisfine** [comment]
Apologies, I forgot to watch the repo.

> I suspect this is due to a difference in which thread is active when the callback is fired for RUBY_INTERNAL_THREAD_EVENT_SUSPENDED 

I just double checked and I don't see any issue. I'll try to find some time to look at your patch in the near future. Feel free to open it as a draft.

**Comment by casperisfine** [comment]
Ok, I figured you issue, I'm going to close this as we can discuss the feature in #4.
